name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (optional, helps with building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build client image
      run: |
        docker build -t actualeyes/multi-client:latest ./client
    - name: Build nginx image
      run: |
        docker build -t actualeyes/multi-nginx:latest ./client
    - name: Build server image
      run: |
        docker build -t actualeyes/multi-server:latest ./client
    - name: Build worker image
      run: |
        docker build -t actualeyes/multi-worker:latest ./client
    - name: List images
      run: |
        docker image ls
    # Push the Docker image to Docker Hub
    - name: Push client image
      run: |
        docker push actualeyes/multi-client:latest
    - name: Push nginx image
      run: |
        docker push actualeyes/multi-nginx:latest
    - name: Push server image
      run: |
        docker push actualeyes/multi-server:latest
    - name: Push worker image
      run: |
        docker push actualeyes/multi-worker:latest

